# Base image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./requirements.txt requirements.txt
RUN pip install -r ./requirements.txt

# Copy application code
COPY . .

# Run the application
CMD ["python", "mqtt_ingestion.py"]
